# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a99f43a37c6f83624f2b9fcf3db7ab0134480fed3f153b0c96687d91daf5c916ebd51a86d110a5b81e82c3f2104f68e2f57466140e1735a802fabc593268621

test:
  secret_key_base: b7983cb6c4aa059c4b0adc5582658be458370b67bbf80a5ac07f3b6cbafa37de5cf913fda3e5da7dc7613bafe12b4b2f3037dc2dd86e9c75759affd106edc42d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
